Name:           ros-lunar-xv-11-laser-driver
Version:        0.3.0
Release:        0%{?dist}
Summary:        ROS xv_11_laser_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/xv_11_laser_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-sensor-msgs

%description
Neato XV-11 Laser Driver. This driver works with the laser when it is removed
from the XV-11 Robot as opposed to reading scans from the Neato's USB port.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Mar 22 2017 rohan <send2arohan@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

